### ISSUE TITLE
Maximum update depth exceeded in react

### ISSUE THREAD

**Issue by lence-wl** [NorthwoodsSoftware/gojs-react-basic#17] opened 2023-02-10 09:31 UTC
`new go.Binding("strokeDashArray", "strokeDashArray").makeTwoWay()

\\\\\\\\\\
{ key: 0, text: "Alpha", color: "lightblue", loc: "0 0", strokeDashArray: [10, 20] },

`

**Comment by jonchardy** [comment] 2023-02-10 13:27
Closing as duplicate of #18.

**Closed by jonchardy** 2023-02-10 13:27 UTC
